### ISSUE TITLE
sktime - Test Framework Development

### ISSUE THREAD

**Issue by RobotPsychologist** [RobotPsychologist/bg_control#105]

**Comment by alyssadsouza** [comment]
> @ShivamJ07 @alyssadsouza this is ready to be picked up, please reply to this comment so I can assign you this task!

Sounds good, assign me to this task please!

**Comment by ShivamJ07** [comment]
> @ShivamJ07 @alyssadsouza this is ready to be picked up, please reply to this comment so I can assign you this task!

Sounds good!

**Comment by fkiraly** [comment]
Just for clarification, who is working on test class and who on the base classes?

**Comment by RobotPsychologist** [comment]
Closing this ticket because Franz and Alex merged previous work that covers this.
