### ISSUE TITLE
skchange integration - registry - adding detection ruberic

### ISSUE THREAD

**Issue by RobotPsychologist** [RobotPsychologist/bg_control#125]
**Parent Issue:** #106 skchange integration - registry

@gavinkatz001 I'm creating a meal identification project-specific issue for tracking this, but your development will be within sktime.

Your task: adding a "detection" rubric in the estimator overview: https://github.com/sktime/sktime/issues/7350

**Comment by gavinkatz001** [comment]
commenting to get assigned
