### ISSUE TITLE
skchange integration - registry - add detector specific tags to the tag registry and tags API reference

### ISSUE THREAD

**Issue by RobotPsychologist** [RobotPsychologist/bg_control#127]
Parent Issue: https://github.com/RobotPsychologist/bg_control/issues/106 skchange integration - registry

@liya-zhu I'm creating a meal identification project-specific issue for tracking this, but your development will be within sktime.

Your task: Add detector specific tags to the tag registry and tags API reference.

**Comment by liya-zhu** [comment]
Hi please assign me :)
