### ISSUE TITLE
Selective review of offline change point detection methods @RobotPsychologist

### ISSUE THREAD

**Issue by RobotPsychologist** [RobotPsychologist/bg_control#138]
## Review of Selective review of offline change point detection methods

**Paper**: https://www.sciencedirect.com/science/article/pii/S0165168419303494?via%3Dihub

Charles Truong, Laurent Oudre, Nicolas Vayatis,
Selective review of offline change point detection methods,
Signal Processing,
Volume 167,
2020,
107299,
ISSN 0165-1684,
https://doi.org/10.1016/j.sigpro.2019.107299.
(https://www.sciencedirect.com/science/article/pii/S0165168419303494)

### Abstract: 
This article presents a selective survey of algorithms for the offline detection of multiple change points in multivariate time series. A general yet structuring methodological strategy is adopted to organize this vast body of work. More precisely, detection algorithms considered in this review are characterized by three elements: a cost function, a search method and a constraint on the number of changes. Each of those elements is described, reviewed and discussed separately. Implementations of the main algorithms described in this article are provided within a Python package called ruptures.
Keywords: Change point detection; Segmentation; Statistical signal processing

### Highlights (from source)
* A structured and didactic review of more than 140 articles related to offline change point detection. Thanks to the methodological framework proposed in this survey, all methods are presented as the combination of three functional blocks, which facilitates comparison between the different approaches.
* The survey provides details on mathematical as well as algorithmic aspects such as complexity, asymptotic consistency, estimation of the number of changes, calibration, etc.
* The review is linked to a Python package that includes most of the presented methods, and allows the user to perform experiments and bench- marks.

### Referred Papers:

* B.E. Brodsky, B.S. Darkhovsky, Nonparametric methods in change point prob-
lems, Springer Netherlands, 1993.
* J. Chen, A.K. Gupta, Parametric Statistical Change Point Analysis: With Appli-
cations to Genetics, Medicine, and Finance, Springer Science & Business Me-
dia, 2011.
* [A Tutorial on Hidden Markov Models and Selected Applications in Speech Recognition](https://www.scopus.com/record/display.uri?eid=2-s2.0-0024610919&origin=inward)
* [Dirichlet Process Hidden Markov Multiple Change-point Model](https://projecteuclid.org/journals/bayesian-analysis/volume-10/issue-2/Dirichlet-Process-Hidden-Markov-Multiple-Change-point-Model/10.1214/14-BA910.full)
* [On a Nonparametric Change Point Detection Model in Markovian Regimes](https://projecteuclid.org/journals/bayesian-analysis/volume-9/issue-4/On-a-Nonparametric-Change-Point-Detection-Model-in-Markovian-Regimes/10.1214/14-BA878.full)
* [Product Partition Models for Change Point Problems](https://www.jstor.org/stable/2242159)
* [A Bayesian Analysis for Change Point Problems](https://www.tandfonline.com/doi/abs/10.1080/01621459.1993.10594323)
* [A survey of methods for time series change point detection](https://link.springer.com/article/10.1007/s10115-016-0987-z)
* [Multiple Change-Point Detection: A Selective Overview](https://projecteuclid.org/journals/statistical-science/volume-31/issue-4/Multiple-Change-Point-Detection-A-Selective-Overview/10.1214/16-STS587.full)

**Comment by RobotPsychologist** [comment]
This was an excellent paper covering statistical techniques for change point detection but does not get into supervised approaches for change point detection (outside of a brief review which referenced the following papers:

- [Learning smoothing models of copy number profiles using breakpoint annotations](https://link.springer.com/article/10.1186/1471-2105-14-164)
- [PeakSeg: constrained optimal segmentation and supervised penalty learning for peak detection in count data](https://proceedings.mlr.press/v37/hocking15.html)
- [Penalty learning for changepoint detection](https://ieeexplore.ieee.org/abstract/document/8081473)
- [Large-Margin Metric Learning for Constrained Partitioning Problems](https://proceedings.mlr.press/v32/lajugie14.html)
- [Supervised Kernel Change Point Detection with Partial Annotations](https://ieeexplore.ieee.org/abstract/document/8683471)

The most useful aspect of this paper is the overview of the cost functions. 

I would focus on the cost functions from Table 2 listed with known K (change points count) first, and prioritize parametric over non-parametric.

**Comment by fkiraly** [comment]
@RobotPsychologist, I have looked into the paper - this is the companion paper to `ruptures` if I understand correctly.

My main comments below:

* the taxonomy in table 2 is not the "top level" taxonomy, but a sub-level taxonomy focusing on methodological details rather than scientific type (learning task or purpose)
* all algorithms in the paper are *of the same, single type* - change-point detection, off-line/batch (no update), single time series, unsupervised.
* the sub-level taxonomy implies that these algorithms come in families, that can probably be mapped on composition patterns. There are only six top-level algorithms reviewed in the paper: binary segmentation, Opt, Pelt, Win, Fused Lasso. Each of these uses a search method and a cost function, objects in their own right - for which it would make sense to define their own base classes
    * @tveten has already recognized this in `skchange` for the cost function - see https://github.com/NorskRegnesentral/skchange/issues/23 - and is implementing a composable design
    * there is another interesting property in this sub-level taxonomy - whether the algorithm requires the "number of changepoints" in advance, or whether it can estimate it. Perhaps that is also an interesting interface point to think about.
