### ISSUE TITLE
Data Generation Pipeline Enhancements

### ISSUE THREAD

**Issue by Phiruby** [RobotPsychologist/bg_control#146]
Things to add to the data generation pipeline:
1. Add a parameter ($\lambda$) so that if there are NaN (consecutive) readings for more than $\lambda$ time, then we drop the entire day. If less than that, just drop the consecutive NaN values.

**Comment by RobotPsychologist** [comment]
git fetch origin
git checkout 146-data-generation-pipeline-enhancements
