### ISSUE TITLE
Data cleaning and generation scrip bugs

### ISSUE THREAD

**Issue by Tony911029** [RobotPsychologist/bg_control#147]
There are a few bugs as described in this ticket:
https://github.com/RobotPsychologist/bg_control/pull/142

## Data Cleaning and Generation Scripts (From the meeting on Wednesday):
- Modified the handling of low-carb meals:
 - Instead of skipping meals with carbs below the threshold, changed msg_type to LOW_CARB_MEAL.
 - Removed resampling before splitting data into meal and non-meal DataFrames.
 - Made the coerce interval configurable (replacing the fixed 5-minute interval).
 - Fixed food_g_keep (it was broken previously).

## Pydantic Update:
Updated Pydantic configurations to address deprecation:

## Update to coerce_function to avoid side affect:
Modified coerce_function to prevent it from altering the index or converting data types.

## BGL Validation Values:
Updated validation values for blood glucose levels (BGL).

## File Naming Convention:
Renamed files to follow the established naming convention.

## Data Generation Bug Fix:
There are bugs in data generation. THe function doesn't run
Requested a simple unit test to verify the fix.

## Data Regeneration:
Regenerated the data to apply all of the above fixes.

**Comment by andytubeee** [comment]
,

**Comment by fkiraly** [comment]
I would suggest to list them in the preamble of this issue.

**Comment by RobotPsychologist** [comment]
Does this need to be an open issue or can this be closed?

**Comment by Tony911029** [comment]
This can be closed. Thanks!
