### ISSUE TITLE
Data generation script improvement 

### ISSUE THREAD

**Issue by Tony911029** [RobotPsychologist/bg_control#149]
Here are some improvements we can make to the data generation scripts
1. Add `n_top_carb_meals` to the labelled.
2. Improve the labeller. The name is a bit too long. We can assign one character to one function.
 - `i` for coerce_time,
 - `d` for dayStart
 - `c` for minCarb, 
 - `l` for meal length, 
 - `n` for top n meals

For example
| Old | New |
|-----|-----|
|Old  |`2024-11-14_500030__timeInter5mins_dayStart4hrs_minCarb5g_2hrMealW`  |
|New |`2024-11-14_500030_i5_d4_c5_l2_n3`|

2. We also will need a parameter that allows us to override the data. First, check out the generated name, and check if the name already exists in the interim folder. If yes, don't generate the file again unless the `forced` flag is true.

**Comment by RobotPsychologist** [comment]
Created a branch for you:
git fetch origin
git checkout 149-data-generation-script-improvement

**Comment by Tony911029** [comment]
PR has been merged so closed!
