### ISSUE TITLE
Data Generation of Simulated Simglucose Data

### ISSUE THREAD

**Issue by RobotPsychologist** [RobotPsychologist/bg_control#154]
We will also be running experiments on the simglucose simulated data. We'll need to understand how closely we can structure this data to resemble real world data. It would be good to have more data to work with when we get this working.

https://github.com/jxx123/

The results of our implementation would be calling a function with our specifications that can essentially create all of the csvs in this directory: 

https://github.com/jxx123/simglucose/tree/master/examples/results/2017-12-31_17-46-32

**Comment by RobotPsychologist** [comment]
@Tony911029 let me know if you're interested in picking this up. I'll keep adding more details.

**Comment by Tony911029** [comment]
I will take a look!

**Comment by RobotPsychologist** [comment]
Marking this as completed, updates can be put into new tickets.
