### ISSUE TITLE
Side-by-Side Histogram Plot of BGL during meal windows and outside of meal windows

### ISSUE THREAD

**Issue by RobotPsychologist** [RobotPsychologist/bg_control#162]
Because with our change points we are assuming that the data is coming from separate distributions one during a meal and one outside of a meal, we wish to visualize this to see if there are noticeable differences. 

- [ ] One side-by-side plot that shows during meal bgl and outside of meal bgl
- [ ] One side-by-side plot that shows bgl n-differences during meal window and outside of meal window. You should be able to specify the number of time steps.

**Comment by RobotPsychologist** [comment]
@Tony911029 you can pick this one up?

**Comment by Tony911029** [comment]
From @RobotPsychologist 

Hey @Tony911029 should you be adding .devcontainer to your gitignore? 

Also I discussed with @fkiraly today we should try to extend these plots to a sort of "temporal" histogram called a fan chart. 

https://en.wikipedia.org/wiki/Fan_chart_(time_series)

So what we need is another function that allows us to specify the meal length window, and the time delta for first differences, the data will need to be split up or chunked into evenly spaced windows that are the same length as the meal length, then we will plot the temporal histogram like the fan chart where the start of each window corresponds to at t=0.
