### ISSUE TITLE
Continuous glucose monitoring for automatic real-time assessment of eating events and nutrition: a scoping review

### ISSUE THREAD

**Issue by RobotPsychologist** [RobotPsychologist/bg_control#173]

**Comment by Cristianofiliped** [comment]
Goal: Understand the approaches to detect meal times used in CGM, compare effectiveness, and relate their applications to automatic bolus adjustments. 

Methods: They searched four databases until October 2023 included publications in English or German that used CGM-based approaches for human (all ages) bolus detection.

The goal of the article is to close a research gap they detected in methods and answer the following guiding questions:
1. Which approaches using CGM for the automatic detection of bolus in (near-)real-time have been investigated, and have these approaches relied solely on CGM or also used other data (e.g., sensors/wearables)?
2. How accurate are these approaches in detecting bolus ?
3. Can these approaches be used in the context of automated bolus?

**Comment by Cristianofiliped** [comment]
**Focus in research**
This summary observes research papers analyzing real-time ingestive activity, using either only rtCGM-based data, or rtCGM plus another some wearable sensor-based methods.

**Most successful methods of detecting ingestive activity**
Some studies used only CGM data. They achieved high sensitivity (≥90%) and low false positive rates (<1 per day), which indicated that additional inputs might not be necessary for effective IA detection. 
Some algorithms that incorporate additional data (i.e Bertrand et al. 's study) but primarily relied on CGM data, might perform similarly with only CGM input. This suggests that CGM-based or CGM-only algorithms can effectively detect IA. 

In addition, a feedback scheme-based algorithm by Godoy et al. achieved high accuracy. Methodological issues, such as relying on meal announcements and insulin boluses, were common in the studies reviewed.

**List of methods involved**
Our review identified a wide range of methods to automatically detect IA, including fuzzy logic, model predictive control, support vector machine, random forest, (extreme) gradient boosting trees, backward difference, Kalman filter estimation, second derivative of glucose, Kalman filters, switching signal generator, simulation-based explanation, classification of horizons, analysis of the glucose trajectory, pattern recognition using linear discriminant analysis, and threshold violation-based approaches. Additionally, adaptive model-based, super-twisting-based, feedback scheme-based, and physiological parameter-invariant-based meal detection approaches were applied.

**Limitation**
I could not find the specific models they used as to contrast the Gluroo model.
