### ISSUE TITLE
Restructure data/interim folder

### ISSUE THREAD

**Issue by Tony911029** [RobotPsychologist/bg_control#194]
In data/Interim folder
We should have something like this.

Data/interim
	|___ 2024-11-15_i5mins_d4hrs_c5g_l5hrs_n4
‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎    -_|___ 679372.csv
‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎    -_|___ 500030.csv
	|___ 2024-11-15_i5mins_d4hrs_c10g_l5hrs_n4
‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎    - _|___ 679372.csv
‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎    - _|___ 500030.csv

The folder name is the {data_config}
Each entry in a folder is a patient 

In the future, if we have 1000 patients, each folder will have 1000 csv

@RobotPsychologist

**Comment by RobotPsychologist** [comment]
Looks great, I think this will make it easier to manage in the long run.
