### ISSUE TITLE
Create .ipynb with a working model for GaussianHMM.

### ISSUE THREAD

**Issue by RobotPsychologist** [RobotPsychologist/bg_control#55]

**Comment by Tony911029** [comment]
I am going to adopt this one!

**Comment by RobotPsychologist** [comment]
Please use the development branch provided:

git fetch origin
git checkout 55-create-ipynb-with-a-working-model-for-gaussianhmm

**Comment by Tony911029** [comment]
@RobotPsychologist Do I still need to push it from the forked project? I don't think I am added as a collaborator of this project so I don't have permission to push to the project.

**Comment by RobotPsychologist** [comment]
Yes, you should push all of your changes to the development fork for now, and then create a pull request that needs to be approved. I can't push to the main branch anymore either. We need to have reviews with this many contributors. 

And yes, the naming convention is outline here in the Open a Notebook section: 
https://cookiecutter-data-science.drivendata.org/using-the-template/

**Comment by Tony911029** [comment]
@RobotPsychologist I dm you on Discord but I don't think you saw it. I am just wondering if you can show me or give me some hints on where to start for this type of task.

**Comment by RobotPsychologist** [comment]
Absolutely I'll reach out to you on discord to discuss.
