### ISSUE TITLE
Model Development - Training Pipeline Script

### ISSUE THREAD

**Issue by RobotPsychologist** [RobotPsychologist/bg_control#92]
### Training Pipeline Script
**Code Location:** /bg_control/0_meal_identification/meal_identification/meal_identification/modeling/train.py

**Requirements:**
1. A model instantiation function that can take a variety of parameter settings.
     1. This function should serve as a hyperparameter training loop: loads the specified dataset, the train_test split, the model choice, the model hyperparameter settings, and perform the fit, test predict, and error calculation.
     2. The function should also write the training runs training logs to models/training_logs directory.
3. A model loading function that can load a model from  0_meal_identification/meal_identification/models
     1. The model should be loadable either fitting or predicting new data
4. A model storing function that stores the trained models in 0_meal_identification/meal_identification/models

#### Useful Resources:
- https://www.sktime.net/en/stable/examples/03b_forecasting_transformers_pipelines_tuning.html

**Comment by NathanL15** [comment]
interested

**Comment by jogong2718** [comment]
interested

**Comment by paulpark6** [comment]
Interested
