### ISSUE TITLE
Dissemination - Github Pages

### ISSUE THREAD

**Issue by RobotPsychologist** [RobotPsychologist/bg_control#97]

**Comment by Tony911029** [comment]
I am thinking we can use React for frontend which should be fairly easy. BE we can use FastAPI. Deploy FE on GitHub page and BE on EC2 instance. If we don't wanna spend any money we can probably use my pc as a server for now.

**Comment by RobotPsychologist** [comment]
> I am thinking we can use React for frontend which should be fairly easy. BE we can use FastAPI. Deploy FE on GitHub page and BE on EC2 instance. If we don't wanna spend any money we can probably use my pc as a server for now.

Okay @ShivamJ07 and @alyssadsouza has some thoughts on this too. What do you think?

**Comment by Tony911029** [comment]
https://tony911029.github.io/blood-glucose-control-live-demo/#/

I created a simple GitHub page here. Seems to be working.

**Comment by alyssadsouza** [comment]
Sorry for the delay! I agree with @Tony911029, a simple React frontend on GH Pages + FastAPI backend would work, we’d just need to sort out hosting for the backend. Ross mentioned that the grad student servers could be an option, which would work just fine for now while the project is still small. However, if we’re expecting a decent amount of traffic as it scales, deploying to AWS would likely be less work for scaling and handling higher traffic.

**EC2 vs Lambda**

Regarding EC2 vs Lambda, I think Lambda is an option worth considering for a couple of reasons. The main difference is that EC2 provides dedicated resources, so if we run a FastAPI/Flask app, it’ll stay running continuously, and we’ll accrue costs even if no one’s using it. EC2 billing is typically per hour or second, as outlined in the [pricing guide](https://aws.amazon.com/ec2/pricing/on-demand/). On the other hand, Lambda is serverless, meaning you're only charged for the time your code is running. The free tier provides [1 million requests per month](https://aws.amazon.com/lambda/pricing/) for free forever.

The choice really depends on what the backend will be doing. Lambda has [time limits](https://docs.aws.amazon.com/lambda/latest/dg/configuration-timeout.html), so long-running tasks that take several minutes could be a reason to reconsider. From what it sounds like, the backend will be running a lot of stateless services (like processing CSVs and running forecasts), so Lambda seems like a good fit. There are lots of resources out there discussing this in more detail; I found [this](https://www.linkedin.com/pulse/aws-lambda-vs-ec2-which-right-your-use-case-mr-a-banerjee/) to be a good article.

**FastAPI vs Flask**

As for FastAPI vs Flask, both will work well, and I don’t think there’s anything too complex about the app that requires the extra features FastAPI offers. However, FastAPI does provide some nice-to-haves, such as:

- Automatic data validation and conversion: If the data is typed incorrectly, it returns a 422 response, ensuring correctness.
- Editor typing support, which is useful for developers.
- API documentation: A built-in API doc endpoint makes it easy for frontend developers to know which endpoints are available and how to use them. You can read more about these benefits in the [docs](https://fastapi.tiangolo.com/tutorial/body/#results).

**Alternative: Streamlit**

Lastly, I wanted to mention Streamlit as an alternative. We used it at my last internship to demo data visualizations, and I think it could work well here too. [Streamlit](https://streamlit.io/) is an open-source framework for creating and deploying interactive web apps for data science and machine learning, using just Python. It handles deployment for you, so there’s no need to worry about managing hosting. It’s especially great for data visualizations, and there are many [demos](https://share.streamlit.io/explore?search=time+series&sort=most+viewed) out there to get a sense of what can be done. The setup is easy, and the learning curve is minimal, especially compared to something like React.

We could deploy the app to a custom subdomain like blood-glucose-control.streamlit.app, and it’s completely free. All we’d need to do is place the app in a subdirectory of our current repo, and Streamlit will automatically trigger a new deployment every time we push changes to GitHub. I can take a day or two to try and get a simple demo running, but anyone is welcome to give it a shot too.

Now, whether this works better than the other options depends on the scale of the app. For simple demos and light traffic, Streamlit should work perfectly. If the computations are heavy or the app sees a lot of traffic, Lambda or EC2 might be better, but I’d need to test those scenarios. The good thing is, Streamlit allows us to get a demo up quickly, and adding documentation pages in markdown is easy too.

@Tony911029 @ShivamJ07 what do you think? Correct me if I'm wrong on any of this.

**Comment by RobotPsychologist** [comment]
I've used streamlit before, and developed a few apps with it:
https://diabeticdreams.streamlit.app/
https://theopen152.streamlit.app/

**Comment by Tony911029** [comment]
@alyssadsouza I have never really used Streamlit before, but I am open to exploring it. I agree with your assessment that React has a significant learning curve. If you are currently occupied with another task, I would be happy to review Streamlit :)

**Comment by alyssadsouza** [comment]
@Tony911029 for sure go for it! @RobotPsychologist I didn't know you've had experience with Streamlit before, what are your thoughts on using it for demoing the project? Does it fit the scale and requirements you envisioned?

**Comment by RobotPsychologist** [comment]
> @Tony911029 for sure go for it! @RobotPsychologist I didn't know you've had experience with Streamlit before, what are your thoughts on using it for demoing the project? Does it fit the scale and requirements you envisioned?

I think it's so easy to use for people that know Python that it's really handy and probably isn't much wasted effort if we start with that and then pivot into FastAPI vs Flask in the future. Streamlit probably doesn't have as much customization as we might like in the future. 

I'm fine with whatever works for now, with the hope of it looking "professional & fancy" in the future. 

I think the number one priority will be getting a backend that works well and is not going to cost us anything in the long run.

**Comment by Tony911029** [comment]
@RobotPsychologist https://blood-glucose-control.streamlit.app/
Here is the streamlit version of the GitHub page. Quick easy to set up and deploy using streamlit community cloud.
